### ISSUE TITLE
UnparsedFlagAccessError

### ISSUE THREAD

**Issue by tagma** [google/model_search#6] opened 2021-02-20 23:50 UTC
Hi - What could be causing this?

---------------------------------------------------------------------------
UnparsedFlagAccessError                   Traceback (most recent call last)
<ipython-input-55-66d895951134> in <module>()
     14     batch_size=32,
     15     experiment_name="animalfaces",
---> 16     experiment_owner="myname")

3 frames
/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in __getattr__(self, name)
    496         # get too much noise.
    497         logging.error(error_message)
--> 498       raise _exceptions.UnparsedFlagAccessError(error_message)
    499 
    500   def __setattr__(self, name, value):

UnparsedFlagAccessError: Trying to access flag --mlmd_default_sqllite_filename before flags were parsed.

**Comment by rgontarek** [comment] 2021-02-21 14:16
I submitted a pull request with the fixes that worked for me. Basically, the flags are being called prior to being loaded. If you want to fix the issue prior to the pull request being merged, you can edit your local files and see the issue is fixed: https://github.com/google/model_search/pull/8

**Comment by srivatsan88** [comment] 2021-02-21 19:30
@tagma .. You can load flags before as @rgontarek had mentioned. In case if you still get unflagged error you can executed the cell I have in my below notebook to load flags. Here is working notebook of installation and on a sample dataset - https://github.com/srivatsan88/YouTubeLI/blob/master/Model_Architecture_Search.ipynb

**Comment by hanna-maz** [comment] 2021-03-03 21:07
This should be fixed in the new version from today.

**Closed by hanna-maz** 2021-03-03 21:07 UTC
